### ISSUE TITLE
code registration and log in pages

### ISSUE THREAD

**Issue by gneisscode** [zuri-training/Team99_anima_lib#3]

**Comment by Eyezallhazy** [comment]
got it!

**Comment by Eyezallhazy** [comment]
code registration and login pages to do
done and dusted 
submitted to team lead for approval
next!!!!

**Comment by gneisscode** [comment]
https://github.com/zuri-training/Team99_anima_lib

**Comment by Eyezallhazy** [comment]
whoop whoop!!!
