### ISSUE TITLE
Prototyping -Interactive components

### ISSUE THREAD

**Issue by draycodes** [zuri-training/Team99_anima_lib#32]
Your task is to search for interactive components that haven't been prototyped and prototype them. You can also turn any feature that should be interactive into a component so that you can prototype them. Interactive components examples are buttons etc...

**Comment by nudsgnr** [comment]
Worked on this. A lot of changes are still being made, so I'd have to return to re-edit them.

**Comment by nudsgnr** [comment]
Re-edited, corrected errors and made sure each component was interactive.
