### ISSUE TITLE
Revisit the Design Thinking Process

### ISSUE THREAD

**Issue by draycodes** [zuri-training/Team99_anima_lib#38]
Based on our work so far, your task is to revisit the design process, search for loopholes and details that have been missed, and revert back to us. You'll have to thoroughly go through our documentation research and designs to achieve this task

**Comment by Thimmo** [comment]
Empathy. 
From our work so far, We have been able to understand the problem we are trying to solve, carrying out extensive background research which has translated to our designs so far being user centered.

Define. 
In the define stage, we identified the problem by making a problem statement; drawing up personas and addressing what needs to be solved. Here we came up with a research plan to help draw out insights from the primary users of the application.

Basic features for authenticated users
•Understanding Animation Libraries
•Implementing Animation libraries in their code
•Customizations that are easy and flexible

After thorough revision of the design, the only loophole I found was that there was no means of email verification before resetting the password. This loophole as at the time of filing this report has been addressed.

**Comment by ezinnejioke** [comment]
We carried out research to test assumptions about how developers who are beginners could access the animation library and be able to implement it. This was done by conducting user interviews with participants. Data collected was analyzed using an empathy map, user persona, and user flow.

Features have been incorporated to enable a smooth usage of the application such as;
Documentation of Animation
Usage examples that enable users in understanding implementation
Every other feature has been incorporated as at the filling of this report.
